site_name: Stack Pub
site_description: Atticus's Docs
site_author: Atticus

# Repository
repo_name: 'Atticus/Stack Pub'
repo_url: 'https://github.com/opfanswyx/StackPub'

# Copyright
copyright: 'Copyright &copy; 2018 - 2019 Atticus'

nav:
  - Hello World: index.md
  - 编程语言:
    - C语言: cprogram/c_data.md
    - C Plus Plus: 
      - C++基础: cplus/cpp_summary.md
      - 类和对象: cplus/cpp_summary.md
      - 引用: cplus/cpp_summary.md
      - 继承与派生: cplus/cpp_summary.md
      - 多态与虚函数: cplus/cpp_summary.md
      - 运算符重载: cplus/cpp_summary.md
      - 模板: cplus/cpp_summary.md
      - 异常: cplus/cpp_summary.md
      - STL: cplus/cpp_summary.md
      - 高级主题: cplus/cpp_summary.md
  - 算法:
    - 数据结构与算法规划: algorithm/plan.md
  - Linux:
    - 规划: linux/plan.md
  - 网络:
    - 规划: network/plan.md
  - 数据库:
    - 规划: database/plan.md
  - 开源项目:
    - 规划: source/plan.md
    - TinyHttpd: source/tinyhttpd.md
  - 数学: 
    - 规划: math/plan.md
  - 图形学:
    - 规划: unity/List.md
    - Unity基础: unity/unity_base.md
    - Shader: unity/unity_shader.md
  - Kit: 
    - 计划: tools/Note.md
    - 基于mkdocs的blog搭建: tools/mkdocs.md
    - VIM常用技巧: tools/vim.md
    - GDB调试的基本使用: tools/gdb.md
    - tmux基本技巧: tools/tmux.md

theme:
  name: material
  language: 'zh'
  palette:
    accent: 'Pink'
  include_search_page: false
  search_index_only: true
  feature:
    tabs: true
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'
  favicon: 'favicon.ico'

extra:
  search:
    language: 'jp'
  manifest: 'manifest.webmanifest'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde