site_name: Stack Pub
site_description: Atticus's Docs
site_author: Atticus
site_url: https://atticuslab.com
strict: false

# Repository
repo_name: 'Atticus/Stack Pub'
repo_url: 'https://github.com/opfanswyx/StackPub'

# Copyright
copyright: 
  Copyright &copy; 2018 - 2019 <a href="https://github.com/opfanswyx">Atticus</a>
  <br><span class="md-footer-custom-text">åšå®¢å†…å®¹éµå®ˆ:</span>
  <a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh">CC BY-SA 4.0 åè®®æ¡æ¬¾</a>


#Contents
nav:
  - ç®€ä»‹: 
    - Hello Wolrd: index.md
    - å­¦ä¹ èµ„æº: index/blogroll.md
    - ä¹¦ç±æ¨èğŸ“š: index/book.md
    - ä¸»é¢˜ä¿®æ”¹: index/theme.md
    - F.A.Q: index/version.md

  - ç¼–ç¨‹è¯­è¨€:
    - C++ Primeræ€»ç»“: 
      - C++ åŸºç¡€: cplus/c++_base.md
      - C++ æ ‡å‡†åº“: cplus/c++_stu.md
      - C++ ç±»: cplus/c++_oop.md
    - Cè¯­è¨€: 
      - Cè¯­è¨€åŸºç¡€: cprogram/c_base.md
      - Cè¯­è¨€ä¸é¢å‘å¯¹è±¡: cprogram/c_object.md
      - Cè¯­è¨€è®¾è®¡æ¨¡å¼: 
        - çŠ¶æ€æ¨¡å¼: cprogram/c_design/c_state.md
        - æ¨¡æ¿æ–¹æ³•æ¨¡å¼: cprogram/c_design/c_template.md
        - è§‚å¯Ÿè€…æ¨¡å¼: cprogram/c_design/c_observer.md
        - è´£ä»»é“¾æ¨¡å¼: cprogram/c_design/c_chain.md
        - è®¿é—®è€…æ¨¡å¼: cprogram/c_design/c_visitor.md
    - æ­£åˆ™è¡¨è¾¾å¼: source/regexp.md
    - Shellç¼–ç¨‹: source/shell.md 
    - Goè¯­è¨€:
      - Goè¯­è¨€åŸºç¡€: goprogram/go_study.md
      - Goè¯­è¨€æºç è§£æ: goprogram/go_source.md
    - PHP: 
      - PHPåŸºç¡€: source/php/php_base.md
      - PHPé¢å‘å¯¹è±¡: source/php/php_object.md
      - PHP WEBç›¸å…³: source/php/php_web.md
    - Luaæ€»ç»“: source/lua/lua_summary.md
  - æ•°æ®ç»“æ„ä¸ç®—æ³•:
    - æœ¬æ¨¡å—è§„åˆ’: algorithm/task.md
    - é“¾è¡¨:
      - é¡ºåºé“¾è¡¨: algorithm/struct_seqlist.md 
      - é“¾å¼é“¾è¡¨: algorithm/struct_linklist.md 
      - é“¾è¡¨çš„å„ç§æ“ä½œ: algorithm/struct_listfunction.md 
      - åŒå‘é“¾è¡¨: algorithm/struct_dlist.md 
      - å¾ªç¯â™»ï¸é“¾è¡¨: algorithm/struct_clist.md 
    - æ ˆä¸é˜Ÿåˆ—: algorithm/struct_stack_queue.md
    - æ ‘ğŸŒ²: algorithm/struct_tree.md
    - å›¾: algorithm/struct_graph.md
    - æ¨¡å¼åŒ¹é…: algorithm/algo_pattern.md
    - æ’åº: algorithm/algo_sort.md
    - æŸ¥æ‰¾: algorithm/algo_sort.md
    - æ•°æ®å‹ç¼©: algorithm/algo_sort.md
    - å†…å­˜ç®¡ç†: algorithm/algo_sort.md
    - åŠ¨æ€è§„åˆ’: algorithm/algo_sort.md
  - æ“ä½œç³»ç»Ÿ:
    - Linux:
      - Linuxå¸¸ç”¨å‘½ä»¤: os/linux/linux_command.md
      - Linuxç¼–ç¨‹åŸºç¡€: os/linux/linux_program.md
    - CSAPP NOTE: 
      - è§„åˆ’: os/csapp/plan.md
      - è®¡ç®—æœºç³»ç»Ÿæ¼«æ¸¸: os/csapp/chapter1.md
  - è®¡ç®—æœºç½‘ç»œ:
    - è§„åˆ’: network/plan.md
  - æ•°æ®åº“:
    - è§„åˆ’: database/plan.md
  - å¼€æºé¡¹ç›®:
    - Nginx:
      - Nginxå®‰è£…ä¸åŸºæœ¬é…ç½®: source/nginx/nginx_base.md
      - WebæœåŠ¡æ­å»ºä¸æ¨¡å—åŒ–é…ç½®: source/nginx/nginx_web.md
      - è´Ÿè½½å‡è¡¡ä¸ç¼“å­˜: source/nginx/nginx_balence.md
      - é«˜å¯ç”¨è´Ÿè½½å‡è¡¡é›†ç¾¤: source/nginx/nginx_high.md
    - Redis:
      - RedisåŸºç¡€: source/redis/redis_base.md
    - TinyHttpd: source/tinyhttpd.md
  - æ•°å­¦: 
    - å›¾å½¢å­¦ç›¸å…³æ•°å­¦: math/math_graph.md
  - å›¾å½¢å­¦:
    - è§„åˆ’: unity/List.md
    - UnityåŸºç¡€: unity/unity_base.md
    - Shader: unity/unity_shader.md
  - LeetCode: 
    - ä¸¤æ•°ä¹‹å’Œ: leetcode/1.two-sum.md
  - ç»éªŒæ€»ç»“ğŸ”§: 
    - ç¼–ç¨‹è§„èŒƒ: kit/code_style.md
    - åŸºäºmkdocsçš„blogæ­å»º: kit/mkdocs.md
    - VIMå¸¸ç”¨æŠ€å·§: kit/vim.md
    - GDBè°ƒè¯•çš„åŸºæœ¬ä½¿ç”¨: kit/gdb.md
    - tmuxåŸºæœ¬æŠ€å·§: kit/tmux.md

theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'Teal'
    accent: 'Pink'
  include_search_page: false
  search_index_only: true
  favicon: 'favicon.ico'
  feature:
    tabs: true
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'
  

extra:
  search:
    language: 'jp'
  disqus: 'Atticus'
  manifest: 'manifest.webmanifest'
  social:
    - type: envelope
      link: mailto:opfanswyx@outlook.com
    - type: github
      link: https://github.com/opfanswyx
    - type: telegram
      link: https://t.me/stackpub
    - type: qq
      link: //shang.qq.com/wpa/qunwpa?idkey=2ffaaf5a3df5fbb57aa50e84469c9eff6c7a960b4ca4b893317c8583398eb6be
    - type:
      link: 1L6mFa2BMPghfn8dPWyNAmxY8iHejM5xgm


extra_javascript:
  - '_static/js/extra.js?v=15'
  - '_static/js/baidu-tongji.js'
  - 'https://cdnjs.loli.net/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML'

#extra_css:
#  - '_static/css/extra.css?v=12'


markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde